/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	k8sovnorgv1 "k8s-programming-tutorial/typeClient/pkg/apis/k8s.ovn.org/v1"
	versioned "k8s-programming-tutorial/typeClient/pkg/client/clientset/versioned"
	internalinterfaces "k8s-programming-tutorial/typeClient/pkg/client/informers/externalversions/internalinterfaces"
	v1 "k8s-programming-tutorial/typeClient/pkg/client/listers/k8s.ovn.org/v1"
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VPCNetworkInformer provides access to a shared informer and lister for
// VPCNetworks.
type VPCNetworkInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.VPCNetworkLister
}

type vPCNetworkInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewVPCNetworkInformer constructs a new informer for VPCNetwork type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVPCNetworkInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVPCNetworkInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredVPCNetworkInformer constructs a new informer for VPCNetwork type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVPCNetworkInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.K8sV1().VPCNetworks().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.K8sV1().VPCNetworks().Watch(context.TODO(), options)
			},
		},
		&k8sovnorgv1.VPCNetwork{},
		resyncPeriod,
		indexers,
	)
}

func (f *vPCNetworkInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVPCNetworkInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *vPCNetworkInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&k8sovnorgv1.VPCNetwork{}, f.defaultInformer)
}

func (f *vPCNetworkInformer) Lister() v1.VPCNetworkLister {
	return v1.NewVPCNetworkLister(f.Informer().GetIndexer())
}
